'use client';

/**
 * v2 design-tweaks sheet — for CVs generated by the new cv-engine.
 *
 * Three tabs:
 *   - Visual    — recipe (visual direction) picker + font + pageMode
 *   - Kleur     — OKLch L/C/H sliders per role, bounded by recipe.palette.{role}.range
 *   - Inhoud    — emphasis fields (only those the recipe enables)
 *
 * Lives next to the v1 `design-tweaks-sheet.tsx`. The wrapper (also in this
 * folder, exported as `DesignTweaksSheet`) routes on `tokens.engineVersion`.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { RotateCcw } from 'lucide-react';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from '@/components/ui/sheet';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Slider } from '@/components/ui/slider';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { toast } from 'sonner';
import { useAuth } from '@/components/auth/auth-context';
import type { CVStyleTokensV2, PageMode } from '@/lib/cv-engine/tokens';
import type { DesignSpec, PaletteRole, FontPairingId, OklchValue } from '@/lib/cv-engine/spec';
import { getRecipeById, listRecipesByRoute } from '@/lib/cv-engine/recipes/registry';
import { clampOklch } from '@/lib/cv-engine/render/css/oklch';

const ROLES: PaletteRole[] = ['ink', 'paper', 'accent', 'muted', 'surface'];

const ROLE_LABELS: Record<PaletteRole, string> = {
  ink: 'Inkt (tekst)',
  paper: 'Papier (achtergrond)',
  accent: 'Accent',
  muted: 'Subtiele tekst',
  surface: 'Oppervlak (sidebar/secties)',
};

type SaveState = 'idle' | 'dirty' | 'saving' | 'saved' | 'error';

interface DesignTweaksSheetV2Props {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  tokens: CVStyleTokensV2;
  originalTokens: CVStyleTokensV2 | null;
  cvId: string;
  onTokensChange: (tokens: CVStyleTokensV2) => void;
}

export function DesignTweaksSheetV2({
  open,
  onOpenChange,
  tokens,
  originalTokens,
  cvId,
  onTokensChange,
}: DesignTweaksSheetV2Props) {
  const { refreshToken } = useAuth();
  const recipe = useMemo(() => getRecipeById(tokens.recipeId), [tokens.recipeId]);
  const candidates = useMemo(
    () => (recipe ? listRecipesByRoute(recipe.route) : []),
    [recipe],
  );

  const [saveState, setSaveState] = useState<SaveState>('idle');
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // ============ Persist ============

  const persist = useCallback(
    (next: CVStyleTokensV2) => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
      setSaveState('dirty');
      debounceRef.current = setTimeout(async () => {
        setSaveState('saving');
        try {
          await refreshToken?.();
          const res = await fetch(`/api/cv/${cvId}/tokens`, {
            method: 'PATCH',
            headers: { 'Content-Type': 'application/json' },
            credentials: 'include',
            body: JSON.stringify({ designTokens: next }),
          });
          if (!res.ok) throw new Error(`HTTP ${res.status}`);
          setSaveState('saved');
          setTimeout(() => setSaveState('idle'), 1200);
        } catch (err) {
          console.error('[design-tweaks-v2] PATCH failed:', err);
          setSaveState('error');
          toast.error('Tweak niet opgeslagen — probeer opnieuw');
        }
      }, 500);
    },
    [cvId, refreshToken],
  );

  // Cleanup pending debounce on unmount.
  useEffect(() => {
    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, []);

  // ============ Mutation helpers ============

  const update = useCallback(
    (next: CVStyleTokensV2) => {
      onTokensChange(next);
      persist(next);
    },
    [onTokensChange, persist],
  );

  const setRecipe = (recipeId: string) => {
    if (recipeId === tokens.recipeId) return;
    // Switching recipes resets palette/font overrides — they were bounded by
    // the old recipe's ranges and won't make sense for the new one.
    update({
      ...tokens,
      recipeId,
      paletteOverride: undefined,
      fontOverride: undefined,
    });
  };

  const setOklchChannel = (role: PaletteRole, channel: 'l' | 'c' | 'h', value: number) => {
    if (!recipe) return;
    const current: OklchValue =
      (tokens.paletteOverride?.[role] as OklchValue | undefined) ??
      recipe.palette[role].anchor;
    const proposed: OklchValue = { ...current, [channel]: value };
    const clamped = clampOklch(proposed, recipe.palette[role].range);
    update({
      ...tokens,
      paletteOverride: { ...(tokens.paletteOverride ?? {}), [role]: clamped },
    });
  };

  const setFont = (font: FontPairingId | 'recipe-default') => {
    update({
      ...tokens,
      fontOverride: font === 'recipe-default' ? undefined : font,
    });
  };

  const setPageMode = (mode: PageMode) => {
    update({ ...tokens, pageMode: mode });
  };

  const setEmphasis = (key: keyof CVStyleTokensV2['emphasis'], value: string | string[] | undefined) => {
    update({ ...tokens, emphasis: { ...tokens.emphasis, [key]: value } });
  };

  const resetAll = () => {
    if (!originalTokens) return;
    update(originalTokens);
    toast.success('Stijl teruggezet naar AI-versie');
  };

  // ============ Guard ============

  if (!recipe) {
    return (
      <Sheet open={open} onOpenChange={onOpenChange}>
        <SheetContent side="right" className="w-[420px] sm:max-w-[420px]">
          <SheetHeader>
            <SheetTitle>Stijl tweaken</SheetTitle>
          </SheetHeader>
          <p className="mt-4 text-sm text-muted-foreground">
            Recipe <code>{tokens.recipeId}</code> niet gevonden in registry.
          </p>
        </SheetContent>
      </Sheet>
    );
  }

  const hasOverride = !!tokens.paletteOverride || !!tokens.fontOverride;

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-[420px] sm:max-w-[420px] overflow-y-auto">
        <SheetHeader className="space-y-1">
          <SheetTitle>Stijl tweaken</SheetTitle>
          <SheetDescription>
            Wijzigingen worden automatisch opgeslagen.{' '}
            <SaveIndicator state={saveState} />
          </SheetDescription>
        </SheetHeader>

        <Tabs defaultValue="visual" className="mt-4">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="visual">Visual</TabsTrigger>
            <TabsTrigger value="color">Kleur</TabsTrigger>
            <TabsTrigger value="content">Inhoud</TabsTrigger>
          </TabsList>

          {/* ============ Visual tab ============ */}
          <TabsContent value="visual" className="space-y-6 mt-4">
            <section className="space-y-2">
              <Label className="text-xs uppercase tracking-wide text-muted-foreground">
                Visuele richting
              </Label>
              <div className="space-y-1.5">
                {candidates.map(c => (
                  <RecipeOption
                    key={c.id}
                    recipe={c}
                    selected={c.id === tokens.recipeId}
                    onSelect={() => setRecipe(c.id)}
                  />
                ))}
              </div>
            </section>

            <section className="space-y-2">
              <Label className="text-xs uppercase tracking-wide text-muted-foreground">
                Lettertype
              </Label>
              <Select
                value={tokens.fontOverride ?? 'recipe-default'}
                onValueChange={v => setFont(v as FontPairingId | 'recipe-default')}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="recipe-default">
                    Recipe-default ({recipe.allowedFontPairings[0]})
                  </SelectItem>
                  {recipe.allowedFontPairings.map(f => (
                    <SelectItem key={f} value={f}>
                      {f}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </section>

            <section className="space-y-2">
              <div className="flex items-center justify-between">
                <Label htmlFor="single-long">PDF als één lange pagina</Label>
                <Switch
                  id="single-long"
                  checked={(tokens.pageMode ?? 'a4-paged') === 'single-long'}
                  onCheckedChange={checked => setPageMode(checked ? 'single-long' : 'a4-paged')}
                />
              </div>
              <p className="text-xs text-muted-foreground">
                Aan: één lange pagina, geen page-breaks. Uit: standaard A4-paging.
              </p>
            </section>

            {hasOverride && originalTokens && (
              <Button variant="outline" size="sm" onClick={resetAll} className="w-full">
                <RotateCcw className="w-3 h-3 mr-2" />
                Terug naar AI-versie
              </Button>
            )}
          </TabsContent>

          {/* ============ Color tab ============ */}
          <TabsContent value="color" className="space-y-5 mt-4">
            {ROLES.map(role => (
              <ColorRoleRow
                key={role}
                role={role}
                label={ROLE_LABELS[role]}
                recipe={recipe}
                value={tokens.paletteOverride?.[role] ?? recipe.palette[role].anchor}
                onChange={(channel, value) => setOklchChannel(role, channel, value)}
              />
            ))}
          </TabsContent>

          {/* ============ Content tab — emphasis fields ============ */}
          <TabsContent value="content" className="space-y-5 mt-4">
            <EmphasisField
              label="Naam-tagline"
              hint="Monocle-stijl, 2-6 woorden onder je naam (bv. 'Strategist, writer, gardener')"
              value={tokens.emphasis.nameTagline ?? ''}
              maxLength={80}
              onChange={v => setEmphasis('nameTagline', v || undefined)}
            />

            {recipe.decorators.dropCap && (
              <EmphasisField
                label="Drop-cap letter"
                hint="Eén karakter — de grote initiaal in je samenvatting"
                value={tokens.emphasis.dropCapLetter ?? ''}
                maxLength={1}
                onChange={v => setEmphasis('dropCapLetter', v || undefined)}
              />
            )}

            {recipe.decorators.pullQuote && (
              <>
                <EmphasisField
                  label="Pull-quote tekst"
                  hint="Eén zin uit je werkervaring die uitgelicht wordt"
                  value={tokens.emphasis.pullQuoteText ?? ''}
                  maxLength={240}
                  onChange={v => setEmphasis('pullQuoteText', v || undefined)}
                />
                <EmphasisField
                  label="Pull-quote attributie"
                  hint="Bv. '— Lead Engineer, Adyen'"
                  value={tokens.emphasis.pullQuoteAttribution ?? ''}
                  maxLength={80}
                  onChange={v => setEmphasis('pullQuoteAttribution', v || undefined)}
                />
              </>
            )}

            {recipe.decorators.posterLine && (
              <EmphasisField
                label="Poster-zin"
                hint="De grote zin in poster-formaat (bij manifesto / poster shape)"
                value={tokens.emphasis.posterLine ?? ''}
                maxLength={160}
                onChange={v => setEmphasis('posterLine', v || undefined)}
              />
            )}

            {recipe.decorators.heroNumeral && (
              <EmphasisField
                label="Hero-cijfer"
                hint="Korte tekst (bv. '8' voor 8 jaar ervaring)"
                value={tokens.emphasis.heroNumeralValue ?? ''}
                maxLength={12}
                onChange={v => setEmphasis('heroNumeralValue', v || undefined)}
              />
            )}

            <section className="space-y-2">
              <Label className="text-xs uppercase tracking-wide text-muted-foreground">
                Accent-keywords
              </Label>
              <Input
                value={(tokens.emphasis.accentKeywords ?? []).join(', ')}
                onChange={e => {
                  const list = e.target.value
                    .split(',')
                    .map(s => s.trim())
                    .filter(Boolean)
                    .slice(0, 7);
                  setEmphasis('accentKeywords', list.length ? list : undefined);
                }}
                placeholder="38%, Postgres, design-system"
              />
              <p className="text-xs text-muted-foreground">
                Komma-gescheiden, max 7. Deze worden in accent-kleur gemarkeerd in body-tekst.
              </p>
            </section>
          </TabsContent>
        </Tabs>
      </SheetContent>
    </Sheet>
  );
}

// ============ Subcomponents ============

function SaveIndicator({ state }: { state: SaveState }) {
  switch (state) {
    case 'idle':
      return null;
    case 'dirty':
    case 'saving':
      return <span className="text-xs text-muted-foreground">Opslaan…</span>;
    case 'saved':
      return <span className="text-xs text-green-600">Opgeslagen ✓</span>;
    case 'error':
      return <span className="text-xs text-red-600">Fout bij opslaan</span>;
  }
}

function RecipeOption({
  recipe,
  selected,
  onSelect,
}: {
  recipe: DesignSpec;
  selected: boolean;
  onSelect: () => void;
}) {
  const accent = recipe.palette.accent.anchor;
  return (
    <button
      type="button"
      onClick={onSelect}
      className={`w-full text-left p-3 rounded-md border transition-colors ${
        selected
          ? 'border-foreground bg-accent/30'
          : 'border-border hover:bg-accent/10'
      }`}
    >
      <div className="flex items-center justify-between gap-2">
        <div className="min-w-0">
          <div className="text-sm font-medium truncate">{recipe.displayName}</div>
          <div className="text-xs text-muted-foreground line-clamp-2 mt-0.5">
            {recipe.description}
          </div>
          <div className="text-[10px] uppercase tracking-wider text-muted-foreground mt-1">
            {recipe.layoutShape} · {recipe.density}
          </div>
        </div>
        <div
          className="w-6 h-6 rounded-full flex-shrink-0 border border-border"
          style={{ backgroundColor: `oklch(${accent.l}% ${accent.c} ${accent.h})` }}
          title={recipe.id}
        />
      </div>
    </button>
  );
}

function ColorRoleRow({
  role,
  label,
  recipe,
  value,
  onChange,
}: {
  role: PaletteRole;
  label: string;
  recipe: DesignSpec;
  value: OklchValue;
  onChange: (channel: 'l' | 'c' | 'h', v: number) => void;
}) {
  const range = recipe.palette[role].range;
  return (
    <section className="space-y-2">
      <div className="flex items-center justify-between">
        <Label className="text-xs uppercase tracking-wide text-muted-foreground">
          {label}
        </Label>
        <div
          className="w-6 h-6 rounded border border-border"
          style={{ backgroundColor: `oklch(${value.l}% ${value.c} ${value.h})` }}
        />
      </div>
      <div className="space-y-1">
        <OklchSlider
          label="L"
          value={value.l}
          min={range.l[0]}
          max={range.l[1]}
          step={0.5}
          onChange={v => onChange('l', v)}
        />
        <OklchSlider
          label="C"
          value={value.c}
          min={range.c[0]}
          max={range.c[1]}
          step={0.005}
          onChange={v => onChange('c', v)}
        />
        <OklchSlider
          label="H"
          value={value.h}
          min={range.h[0]}
          max={range.h[1]}
          step={1}
          onChange={v => onChange('h', v)}
        />
      </div>
    </section>
  );
}

function OklchSlider({
  label,
  value,
  min,
  max,
  step,
  onChange,
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
  onChange: (v: number) => void;
}) {
  // If the range is essentially zero, hide the slider — no tweak to do.
  if (Math.abs(max - min) < step) return null;
  return (
    <div className="flex items-center gap-2">
      <span className="text-[10px] uppercase font-mono w-3 text-muted-foreground">{label}</span>
      <Slider
        value={[value]}
        min={min}
        max={max}
        step={step}
        onValueChange={vals => onChange(vals[0])}
        className="flex-1"
      />
      <span className="text-[10px] font-mono w-12 text-right text-muted-foreground tabular-nums">
        {value.toFixed(step < 0.1 ? 3 : 1)}
      </span>
    </div>
  );
}

function EmphasisField({
  label,
  hint,
  value,
  maxLength,
  onChange,
}: {
  label: string;
  hint?: string;
  value: string;
  maxLength?: number;
  onChange: (v: string) => void;
}) {
  return (
    <section className="space-y-1.5">
      <Label className="text-xs uppercase tracking-wide text-muted-foreground">{label}</Label>
      <Input
        value={value}
        maxLength={maxLength}
        onChange={e => onChange(e.target.value)}
      />
      {hint && <p className="text-xs text-muted-foreground">{hint}</p>}
    </section>
  );
}
