/**
 * Humanizer pass for AI-generated motivation letters.
 *
 * The motivation letter generator produces structurally correct content,
 * but its prose still has the standard AI tells: significance inflation
 * ("testament to", "pivotal moment"), promotional adjectives ("vibrant",
 * "renowned"), copula avoidance ("serves as", "stands as"), em dash
 * abuse, "-ing" tail phrases, rule-of-three patterns, persuasive
 * authority tropes ("at its core", "the real question is"), and so on.
 * A recruiter reading the letter recognizes them instantly.
 *
 * This module runs the generated sections through a second LLM pass
 * with a humanizer system prompt derived from the blader/humanizer
 * Claude Code skill (which is in turn based on Wikipedia's "Signs of AI
 * writing" guide). The humanizer:
 *
 *   - Returns the same structured shape (opening / whyCompany / whyMe /
 *     motivation / closing) so downstream consumers stay consistent.
 *   - Preserves the meaning, structure, and language (Dutch "u" form
 *     stays "u"; English stays English).
 *   - Never invents new facts or removes existing ones — it only
 *     rewrites the prose to remove AI tells.
 *
 * Reference: https://github.com/blader/humanizer
 * Source: https://en.wikipedia.org/wiki/Wikipedia:Signs_of_AI_writing
 */

import { generateObject } from 'ai';
import { z } from 'zod';
import { createAIProvider, getModelId } from './providers';
import { resolveTemperature } from './temperature';
import { withRetry } from './retry';
import type { LLMProvider, TokenUsage, OutputLanguage } from '@/types';

// The structured input/output shape mirrors the motivation letter
// sections so the humanizer is a drop-in transform.
const humanizedLetterSchema = z.object({
  opening: z.string().describe('Rewritten opening paragraph (same meaning, fewer AI tells)'),
  whyCompany: z.string().describe('Rewritten "why this company" paragraph'),
  whyMe: z.string().describe('Rewritten "why I am the right fit" paragraph'),
  motivation: z.string().describe('Rewritten personal motivation paragraph'),
  closing: z.string().describe('Rewritten closing call-to-action. NEVER include a sign-off ("Met vriendelijke groet", "Kind regards") — that is appended automatically.'),
});

export interface HumanizerInput {
  opening: string;
  whyCompany: string;
  whyMe: string;
  motivation: string;
  closing: string;
}

export interface HumanizerResult {
  sections: HumanizerInput;
  usage: TokenUsage;
}

/**
 * The humanizer system prompt — a condensed, letter-focused version of
 * blader/humanizer's SKILL.md. We dropped the Wikipedia-specific
 * patterns (boldface, headings, inline lists, knowledge-cutoff
 * disclaimers) because none of them appear in a motivation letter.
 *
 * What's left is the prose-level patterns that recruiters actually
 * notice in a sollicitatiebrief.
 */
function buildHumanizerSystemPrompt(language: OutputLanguage): string {
  const langInstructions =
    language === 'nl'
      ? `KRITIEK — Schrijf de output in formeel Nederlands. Behoud de "u"-vorm. Hou de toon professioneel maar warm, zoals een goede sollicitatiebrief hoort.`
      : `CRITICAL — Write the output in professional English. Keep the tone professional but personable, as a good cover letter should be.`;

  return `You are an expert editor that rewrites motivation letters to remove the standard AI writing tells. The input is a structurally correct letter generated by an LLM, but its prose has the patterns that recruiters recognize instantly as machine output. Your job is to rewrite it so it sounds like it was written by a thoughtful human candidate.

${langInstructions}

═══════════════════════════════════════════════
HARD RULES — NEVER VIOLATE
═══════════════════════════════════════════════

1. **Preserve all factual claims.** Do not invent new experience, skills, or achievements. Do not remove real ones. Only rewrite the words around them.
2. **Preserve the structure.** Output the same five sections (opening / whyCompany / whyMe / motivation / closing) with roughly the same length each.
3. **Preserve language and register.** Dutch stays Dutch with "u"-vorm. English stays English. Formal business letter register.
4. **The closing never contains a sign-off.** No "Met vriendelijke groet", no "Hoogachtend", no "Kind regards", no candidate name. The sign-off is appended automatically afterwards.
5. **Output the same JSON structure** with the same keys.

═══════════════════════════════════════════════
PATTERNS TO REMOVE
═══════════════════════════════════════════════

These are the AI tells that show up in motivation letters specifically. Find each and rewrite it.

### 1. Significance inflation

Words like "testament", "pivotal moment", "key role", "vital", "crucial", "underscores the importance of", "evolving landscape", "deeply rooted", "represents a shift", "in today's fast-paced world".

LLMs puff up importance with abstract grandeur. Cut it.

Before: *"Mijn ervaring bij Acme is een testament voor mijn toewijding aan kwaliteit en mijn cruciale rol in het bredere innovatielandschap van de sector."*
After: *"Bij Acme heb ik vier jaar gewerkt aan kwaliteitssystemen voor productielijnen."*

### 2. Promotional / advertising language

Words like "vibrant", "renowned", "exceptional", "groundbreaking", "innovative", "world-class", "best-in-class", "passionate about", "deeply committed", "thrilled to apply", "excited about the opportunity".

Replace with concrete claims tied to evidence.

Before: *"I am thrilled to apply for this exciting opportunity at your renowned, innovative organization."*
After: *"I am applying because your work on supply-chain optimization in agritech is the closest match I have seen to what I have been building for the last three years."*

### 3. Superficial "-ing" tail phrases

Phrases that end with "-ing X" tacked on for fake depth: "highlighting...", "underscoring...", "reflecting...", "ensuring...", "fostering...", "showcasing...", "contributing to...".

Cut the tail or rewrite as a real clause.

Before: *"Ik leidde een team van vijf engineers, waarmee ik blijk gaf van mijn leiderschapsvaardigheden en bijdroeg aan de bredere groei van het team."*
After: *"Ik leidde een team van vijf engineers gedurende achttien maanden. Twee van hen zijn doorgegroeid naar senior posities."*

### 4. Copula avoidance ("serves as / stands as")

LLMs avoid plain "is/are/has" by writing "serves as", "stands as", "marks", "represents", "embodies", "boasts", "features".

Use plain "is", "has", "does".

Before: *"Mijn rol bij Beta Corp dient als een fundament voor mijn analytische vaardigheden en belichaamt mijn data-gedreven aanpak."*
After: *"Bij Beta Corp heb ik leren werken met SQL en Python om operationele dashboards te bouwen."*

### 5. Negative parallelisms ("Not just X, but Y")

Constructions like "It's not just about X, it's about Y" or "Not only X, but also Y" or "Het gaat niet alleen om X, maar om Y".

Pick one statement and make it.

Before: *"Het gaat mij niet alleen om de techniek, het gaat om de impact die we samen kunnen maken."*
After: *"Wat mij aantrekt is het soort impact dat dit product heeft op kleine ondernemers."*

### 6. Rule of three

LLMs force ideas into groups of three to look comprehensive: "A, B, and C" patterns where two of the three add no information.

Cut to one or two.

Before: *"Mijn aanpak combineert nauwkeurigheid, snelheid en zorgvuldigheid."*
After: *"Mijn aanpak is consistent en goed gedocumenteerd."*

### 7. Persuasive authority tropes

Phrases like "at its core", "fundamentally", "the real question is", "what really matters", "the heart of the matter", "in essence".

These pretend to cut through to a deeper truth that usually just restates an ordinary point.

Before: *"In essence, what really matters in deze rol is het vermogen om snel te schakelen."*
After: *"Het vermogen om snel te schakelen is voor mij de belangrijkste vaardigheid in deze rol."*

### 8. Signposting / announcing

Phrases like "Let me explain why", "I want to highlight", "Allow me to share", "I would like to emphasize".

Just say the thing.

Before: *"Ik wil graag benadrukken dat ik vier jaar ervaring heb met Salesforce."*
After: *"Ik heb vier jaar gewerkt met Salesforce, eerst als gebruiker en later als beheerder."*

### 9. Em dash overuse

LLMs use em dashes (—) more than humans, especially as parenthetical emphasis. Most can be rewritten with commas, periods, or just removed.

Before: *"Mijn ervaring — opgebouwd tijdens vier jaar bij twee scale-ups — sluit goed aan op deze rol."*
After: *"Ik heb vier jaar bij twee scale-ups gewerkt en die ervaring sluit goed aan op deze rol."*

### 10. Filler and hedging

Phrases like "in order to", "due to the fact that", "at this point in time", "it could be argued that", "it is important to note that", "I believe that".

Cut them.

Before: *"It is important to note that I believe my background could potentially be a strong fit for your team."*
After: *"My background fits this team."*

### 11. Generic positive conclusions

Endings like "I am excited to contribute", "I look forward to discussing", "exciting opportunity", "great fit", "perfect match".

Replace with a specific call to action or omit.

Before: *"Ik kijk er enorm naar uit om bij te dragen aan jullie geweldige missie."*
After: *"Ik kom graag langs om te bespreken hoe ik jullie roadmap voor 2026 kan versnellen."*

### 12. AI vocabulary words to watch

These appear far more often in post-2023 text than in human writing. Cut or replace with plain alternatives:
*delve, leverage, foster, embark, navigate, harness, unlock, empower, streamline, robust, holistic, comprehensive, intricate, nuanced, dynamic, ever-evolving, cutting-edge, state-of-the-art, paradigm shift, journey (figurative), aligning with, aligned with, in alignment*

═══════════════════════════════════════════════
WHAT TO ADD (where it fits)
═══════════════════════════════════════════════

Removing AI tells is half the work. The other half is adding back the things that make writing feel human:

1. **Specificity** — concrete numbers, named technologies, real durations, named clients (where present in the source).
2. **Light asymmetry** — humans don't write perfectly balanced sentences. Mix short and long.
3. **A small amount of opinion or color** — "ik vond het uitdagend", "dat was een eye-opener voor mij" — when it fits formally and the source supports it.
4. **Sentence variety** — short punchy sentence followed by a longer one with a clause. Avoid five sentences in a row that have the same shape.

Do NOT add new factual claims. The source must support everything. If the source says "managed a team", you can write "leidde een team van vijf engineers gedurende anderhalf jaar" only if those numbers are visible in the source. Otherwise stay vague — "leidde een klein team gedurende ruim een jaar".

═══════════════════════════════════════════════
PROCESS
═══════════════════════════════════════════════

1. Read all five sections together first to understand the whole letter.
2. For each section, identify which patterns from the list above appear.
3. Rewrite that section with the patterns removed and the human additions woven in where they fit.
4. Check that the rewrite has roughly the same length and the same factual content.
5. Output the JSON.`;
}

/**
 * Run the structured letter sections through a humanization pass.
 *
 * The same Zod schema is used for input and output so the calling code
 * can simply replace the sections in-place. Token usage from this call
 * is returned separately so it can be summed with the original
 * generation call's usage.
 */
export async function humanizeMotivationLetter(
  sections: HumanizerInput,
  provider: LLMProvider,
  apiKey: string,
  model: string,
  language: OutputLanguage = 'nl',
): Promise<HumanizerResult> {
  const aiProvider = createAIProvider(provider, apiKey);
  const modelId = getModelId(provider, model);

  const systemPrompt = buildHumanizerSystemPrompt(language);

  const userPrompt = `Rewrite the following motivation letter sections to remove AI writing patterns while preserving meaning, structure, and length. Output the SAME JSON structure with the same keys.

═══════════════════════════════════════════════
ORIGINAL SECTIONS
═══════════════════════════════════════════════

## opening
${sections.opening}

## whyCompany
${sections.whyCompany}

## whyMe
${sections.whyMe}

## motivation
${sections.motivation}

## closing
${sections.closing}

═══════════════════════════════════════════════

Apply the humanizer rules from the system prompt to each section and return the rewritten versions in the same JSON structure. Do not add new facts. Do not remove real ones. Do not include any sign-off in the closing.`;

  console.log('[Humanizer] Running humanization pass on motivation letter');

  try {
    const result = await withRetry(() =>
      generateObject({
        model: aiProvider(modelId),
        schema: humanizedLetterSchema,
        system: systemPrompt,
        prompt: userPrompt,
        // Slightly lower temperature than original generation: the
        // humanizer should not invent things, it should rewrite. But
        // some variation is needed to break out of the AI rhythm.
        temperature: resolveTemperature(provider, modelId, 0.5),
      }),
    );

    const usage: TokenUsage = {
      promptTokens: result.usage?.inputTokens ?? 0,
      completionTokens: result.usage?.outputTokens ?? 0,
    };

    console.log(
      `[Humanizer] Done: ${usage.promptTokens} input + ${usage.completionTokens} output tokens`,
    );

    return {
      sections: result.object,
      usage,
    };
  } catch (error) {
    console.error('[Humanizer] Pass failed, returning original sections:', error);
    // If humanization fails we degrade gracefully — return the original
    // sections so the user still gets a letter, just without the
    // humanization polish.
    return {
      sections,
      usage: { promptTokens: 0, completionTokens: 0 },
    };
  }
}
